-- V3__Create_Spring_Session_Tables.sql
-- 在 src/main/resources/db/migration/ 目录下创建此文件

-- 创建Spring Session主表
CREATE TABLE SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

-- 创建索引以提高性能
CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

-- 创建Spring Session属性表
CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BYTEA NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) 
        REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);

-- 添加表注释
COMMENT ON TABLE SPRING_SESSION IS 'Spring Session主表，存储会话基本信息';
COMMENT ON TABLE SPRING_SESSION_ATTRIBUTES IS 'Spring Session属性表，存储会话属性数据';

-- 添加列注释
COMMENT ON COLUMN SPRING_SESSION.PRIMARY_ID IS '主键ID';
COMMENT ON COLUMN SPRING_SESSION.SESSION_ID IS '会话ID';
COMMENT ON COLUMN SPRING_SESSION.CREATION_TIME IS '创建时间（毫秒时间戳）';
COMMENT ON COLUMN SPRING_SESSION.LAST_ACCESS_TIME IS '最后访问时间（毫秒时间戳）';
COMMENT ON COLUMN SPRING_SESSION.MAX_INACTIVE_INTERVAL IS '最大非活动间隔（秒）';
COMMENT ON COLUMN SPRING_SESSION.EXPIRY_TIME IS '过期时间（毫秒时间戳）';
COMMENT ON COLUMN SPRING_SESSION.PRINCIPAL_NAME IS '用户主体名称';