version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: require4testing
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
