spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/require4testing
    username: dev
    password: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
