spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/require4testing
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  session:
    store-type: jdbc
    timeout: 1800
    jdbc:
      initialize-schema: never
    cookie:
      same-site: lax    # ✅ 改为 lax 而不是 none
      secure: false     # ✅ 本地开发设为 false

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: false   # ✅ 本地开发设为 false
        same-site: lax  # ✅ 改为 lax 而不是 none

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG
    org.flywaydb: DEBUG
    org.springframework.security: DEBUG
    com.you.require4testing: DEBUG